### ISSUE TITLE
JSON issue

### ISSUE THREAD

**Issue by dy** [garthenweb/bubleify#5]
There is a package [browser-media-mime-type](http://npmjs.org/package/browser-media-mime-type).
Invoking `browserify index.js -t bubleify` for it raises an error:

```
...browser-media-mime-type>browserify index.js -t bubleify
SyntaxError: Unexpected token (2:14) while parsing file: ...browser-media-mime-type\mime-types.json
    at Parser.pp.raise (...bubleify\node_modules\acorn\dist\acorn.js:923:13)
    at Parser.pp.unexpected (...bubleify\node_modules\acorn\dist\acorn.js:1490:8)
    at Parser.pp.semicolon (...bubleify\node_modules\acorn\dist\acorn.js:1469:73)
    at Parser.pp.parseExpressionStatement (...bubleify\node_modules\acorn\dist\acorn.js:1994:8)
    at Parser.pp.parseStatement (...bubleify\node_modules\acorn\dist\acorn.js:1772:188)
    at Parser.pp.parseBlock (...bubleify\node_modules\acorn\dist\acorn.js:2009:21)
    at Parser.pp.parseStatement (...bubleify\node_modules\acorn\dist\acorn.js:1753:19)
    at Parser.pp.parseTopLevel (...bubleify\node_modules\acorn\dist\acorn.js:1666:21)
    at Parser.parse (...bubleify\node_modules\acorn\dist\acorn.js:1632:17)
    at parse (...bubleify\node_modules\acorn\dist\acorn.js:885:44)

```

**Comment by mattdesl** [comment]
Looks like there is a bug with the transform. It should return a pass through stream (ie no transform) when the file extension is .json. See how other transforms do it:
https://github.com/substack/brfs/blob/master/index.js

**Comment by davidchase** [comment]
had a similar issue as the OP

found https://github.com/babel/babelify/blob/master/index.js#L67 to be helpful as well as @mattdesl suggestion

**Comment by garthenweb** [comment]
Thank you for your feedback. I like to have a look into this in the evening!

**Comment by garthenweb** [comment]
JSON files will be ignored by default in the latest release (v0.5.0).
